keebymeet/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

# Base
from app.views import home

# Users
from app.views.user import (
    profile,
    user_detail)

# Authentication
from app.views.auth import (
    log_out,
    sign_in,
    log_in)

# Posts
from app.views.post import (
    post_create,
    post_detail,
    post_update)

# Keyboards
from app.views.keyboard import keeb_detail

# Other
from app.views.other import not_working_yet

urlpatterns = [
    path("admin/", admin.site.urls)
]

urlpatterns += i18n_patterns(
    # Home
    path("", home.HomeView.as_view(), name="app_home"),
    path("home/", home.HomeView.as_view(), name="app_home"),

    # Authentication
    path("sign-in/", sign_in.signInView, name="app_sign_in"),
    path("log-in/", log_in.logInView, name="app_log_in"),
    path("log-out/", log_out.logOutView, name="app_log_out"),

    # Users
    path("profile/", profile.ProfileView.as_view(), name="app_profile"),
    path("user/<str:slug>", user_detail.UserDetailView.as_view(), name="app_user_detail"),

    # Posts
    path("post/create/", post_create.PostCreateView.as_view(), name="app_post_create"),
    path("post/<int:pk>", post_detail.PostDetailView.as_view(), name="app_post_detail"),
    path("post/update/<int:pk>", post_update.PostUpdateView.as_view(), name="app_post_update"),

    # Keyboards
    path("keeb/<int:pk>", keeb_detail.KeebDetailView.as_view(), name="app_keeb_detail"),

    # Others
    path("NotWorkingYetView", not_working_yet.NotWorkingYetView.as_view(), name="app_not_working_yet")
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import PROTECT
from django.utils.timezone import now


class Person(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)

    birth_date = models.DateField(blank=False,
                                  null=False,
                                  default=None)

    description = models.TextField(blank=True,
                                   null=True,
                                   default=None)

    """
    def __str__(self):
        return '{} ({})'.format(
            self.user,
            ' / '.join([str(c) for c in self.keyboards.all()])
        )
    """


class Keyboard(models.Model):
    name = models.TextField(blank=False,
                            null=False,
                            default=None)

    description = models.TextField(blank=False,
                                   null=False,
                                   default=None)

    keys = models.IntegerField(null=True,
                               default=None)

    release_date = models.DateField(null=True,
                                    default=None)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.TextField(blank=False,
                             null=False,
                             default=None)

    content = models.TextField(blank=False,
                               null=False,
                               default=None)

    creation_date = models.DateTimeField(default=now)

    author = models.ForeignKey(User,
                               null=False,
                               default=1,
                               on_delete=PROTECT)

    featured_keyboards = models.ManyToManyField(Keyboard,
                                                default=1)

    def __str__(self):
        return self.title

app/forms/login.py
from django import forms


class LoginForm(forms.Form):
    user_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 't-input'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 't-input'}))

app/forms/post_create.py
from django import forms


class PostCreateForm(forms.Form):

    attributes = {
        'class': 't-input'
    }

    title = forms.CharField(widget=forms.TextInput(
        attrs=attributes), required=True)
    content = forms.CharField(widget=forms.TextInput(
        attrs=attributes), required=True)

app/forms/sign_in.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username",
                  "email",
                  "password1",
                  "password2"]

app/views/home.py
from django.views.generic import TemplateView

from app.models import Post, Keyboard


class HomeView(TemplateView):
    """Home view."""

    template_name = "home/home.html"

    def get_context_data(self, **kwargs):
        result = super().get_context_data(**kwargs)

        result["posts"] = Post.objects.all().order_by("-creation_date")
        result["keebs"] = Keyboard.objects.all().order_by("name")
        result["title"] = "Home"

        return result

templates/home/home.html
{% extends "templates/default.html" %}

{% load static i18n %}

{% block content %}

    <section class="default s-grey section-buttons">
        {% if user.is_authenticated %}
            <div>{% trans "Hello" %} <a class="t-link green" href="{% url "app_profile" %}">{{ user }}</a>.</div>
        {% else %}
            <div>{% trans "Welcome!" %} <a class="t-link green" href="{% url "app_log_in" %}">{% trans "log-in" %}</a> {% trans "or" %} <a class="t-link green" href="{% url "app_sign_in" %}">{% trans "sign-in" %}</a>.</div>
        {% endif %}
    </section>

    {% for post in posts %}

        <section id="{{ post.pk }}" class="s-post s-lightgrey">

            <div class="aside">
                <!-- Votes. -->
                <div class="votes">
                    <a data-type="vote" href="{% url "app_not_working_yet" %}">
                        <img src="{% static "img/icons/arrow-black-top.svg" %}" alt="Arrow red top">
                    </a>
                    <div class="darkgrey">0</div>
                    <a data-type="vote" href="{% url "app_not_working_yet" %}">
                        <img src="{% static "img/icons/arrow-black-bottom.svg" %}" alt="Arrow red bottom">
                    </a>
                </div>
            </div>

            <div class="main">

                <div class="header">
                    <div class="nav">
                        <p><a class="t-link green" href="{% url "app_user_detail" post.author %}">{{ post.author }}</a></p>
                    </div>
                    <p class="darkgrey">{{ post.creation_date|date:"Y-m-d" }}</p>
                </div>

                <a class="body" href="{% url "app_post_detail" post.pk %}">
                    <h3>{{ post.title }}</h3>
                    <p>{{ post.content }}</p>
                </a>

                <div class="footer">
                    <p><a class="t-link green" href="{% url "app_post_detail" post.pk %}">keeby-talk:~$ fetch -article</a></p>
                    <!--<p class="darkgrey">comments[0]</p>-->
                </div>

            </div>

        </section>

    {% endfor %}

{% endblock %}

templates/keeb/keeb-detail.html
{% extends "templates/keyboard.html" %}

{% load static i18n %}

{% block content %}

    <section class="s-blary-head s-green">

        <h2 class="green">{{ object.name }}</h2>
        <p class="green">{{ object.description }}</p>

    </section>

    <section class="default s-grey section-buttons">

        <a class="t-link green " href="{% url "app_post_create" %}">keeby-talk:~$ <span
                class="grey">post -create -target[{{ object.name }}]</span></a>
        <div>{% trans "total_related_posts" %}[{{ posts.all.count }}]</div>

    </section>

    {% if posts %}

        {% for post in posts.all %}

            <section id="{{ post.pk }}" class="s-post s-lightgrey">

                <div class="aside">
                    <!-- Votes. -->
                    <div class="votes">
                        <a data-type="vote" href="{% url "app_not_working_yet" %}">
                            <img src="{% static "img/icons/arrow-black-top.svg" %}" alt="Arrow red top">
                        </a>
                        <div class="darkgrey">0</div>
                        <a data-type="vote" href="{% url "app_not_working_yet" %}">
                            <img src="{% static "img/icons/arrow-black-bottom.svg" %}" alt="Arrow red bottom">
                        </a>
                    </div>
                </div>

                <div class="main">

                    <div class="header">
                        <div class="nav">
                            <p><a class="t-link green" href="{% url "app_user_detail" post.author %}">{{ post.author }}</a></p>
                        </div>
                        <p class="darkgrey">{{ post.creation_date|date:"Y-m-d" }}</p>
                    </div>

                    <a class="body" href="{% url "app_post_detail" post.pk %}">
                        <h3>{{ post.title }}</h3>
                        <p>{{ post.content }}</p>
                    </a>

                    <div class="footer">
                        <p><a class="t-link green" href="{% url "app_post_detail" post.pk %}">keeby-talk:~$ fetch
                            -article</a>
                        </p>
                        <!--<p class="darkgrey">comments[0]</p>-->
                    </div>

                </div>

            </section>

        {% endfor %}

    {% else %}
        <section class="s-user-hotbar s-grey">
            <p>{% trans "There isn't any post(s) related to the " %}{{ object.name }}{% trans " yet!" %}</p>
        </section>
    {% endif %}

{% endblock %}

templates/other/not-working-yet.html
{% extends "templates/default.html" %}

{% load i18n %}

{% block content %}

    <section class="default s-grey">

        <h2>{% trans "Oops!" %}</h2>

        <p>{% trans "This functionality not working yet" %}.</p>

        <a class="t-link green underline" href="{% url "app_home" %}">keeb-talk:~$ redirect -home</a>

    </section>

{% endblock %}

templates/post/post-create.html
{% extends "templates/default.html" %}

{% load i18n %}

{% block content %}

    <section class="default s-grey">

        <h2>{% trans "post[create]" %}</h2>

        <form action="" method="post">

            {% csrf_token %}

            <section class="s-green s-form">
                <p>{% trans "Chose a least one related keyboard" %}</p>
                <label class="green" for="featured_keyboards">keeby-talk:~$ post -featured_keyboards</label><br>
                <span class="green">keeby-talk:~$ </span><br>
                <!-- Lists all of the keyboards. -->
                {{ form.featured_keyboards }}<br>
                <p>{{ form.featured_keyboards.error }}</p>
            </section>

            <section class="s-form s-lightgrey">
                <p>{% trans "The post's title" %}</p>
                <label class="green" for="title">keeby-talk:~$ title</label><br>
                <span class="green">keeby-talk:~$ </span><br>
                <textarea class="t-input large" name="title" rows="2" cols="50" placeholder="{% trans "Tell us a great title" %}"></textarea>
            </section>

            <section class="s-form s-lightgrey">
                <p>{% trans "The post's content" %}</p>
                <label class="green" for="content">keeby-talk:~$ content -text</label><br>
                <span class="green">keeby-talk:~$ </span><br>
                <textarea class="t-input large" name="content" rows="5" cols="50" placeholder="{% trans "Tell us a great content" %}"></textarea><br><br>
            </section>

            <input class="t-input" type="submit" value="keeby-talk:~$ push -post">

        </form>

    </section>

{% endblock %}

templates/post/post-detail.html
{% extends "templates/default.html" %}

{% load static i18n %}

{% block content %}

    <section class="s-post s-lightgrey">

        <div class="aside">
            <!-- Votes. -->
            <div class="votes">
                <a data-type="vote" href="{% url "app_not_working_yet" %}">
                    <img src="{% static "img/icons/arrow-black-top.svg" %}" alt="Arrow red top">
                </a>
                <div class="darkgrey">0</div>
                <a data-type="vote" href="{% url "app_not_working_yet" %}">
                    <img src="{% static "img/icons/arrow-black-bottom.svg" %}" alt="Arrow red bottom">
                </a>
            </div>
        </div>

        <div class="main">

            <div class="header">
                <div class="nav">
                    <p><a class="t-link green" href="{% url "app_user_detail" post.author %}">{{ post.author }}</a></p>
                    {% if post.author.id == user.pk %}
                        <p class="darkgrey">&nbsp;•&nbsp;<a class="t-link" href="{% url "app_post_update" post.id %}">{% trans "edit" %}</a></p>
                        <p class="darkgrey">&nbsp;•&nbsp;<a class="t-link" href="{% url "app_not_working_yet" %}">{% trans "delete" %}</a></p>
                    {% endif %}
                </div>
                <p class="darkgrey">{{ post.creation_date|date:"Y-m-d" }}</p>
            </div>

            <div class="body">
                <h3>{{ post.title }}</h3>
                <p>{{ post.content }}</p>
            </div>

            <section class="s-form-comment s-lightgrey">
                <h3>{% trans "featured_keyboards" %}[{{ object.featured_keyboards.all.count }}]</h3>
                <ul>
                    {% for keyboard in object.featured_keyboards.all %}
                        <li><p><a class="t-link green"
                                  href="{% url "app_keeb_detail" keyboard.pk %}">{{ keyboard.name }}</a></p></li>
                    {% endfor %}
                </ul>
            </section>

        </div>

    </section>

{% endblock %}

templates/post/post-update.html
{% extends "templates/default.html" %}

{% load i18n %}

{% block content %}

    <section class="default s-grey">

        <h2>{% trans "post[update]" %}</h2>

        <form action="" method="post">

            {% csrf_token %}

            <section class="s-green s-form">
                <p>{% trans "Chose a least one related keyboard" %}</p>
                <label class="green" for="featured_keyboards">keeby-talk:~$ post -featured_keyboards</label><br>
                <span class="green">keeby-talk:~$ </span><br>
                <!-- Lists all of the keyboards. -->
                <select name="featured_keyboards" id="id_featured_keyboards" required="" multiple="">
                    {% for option in form.featured_keyboards %}
                        {% if option %}
                            {{ option }}
                        {% else %}
                            {{ option }}
                        {% endif %}
                    {% endfor %}
                </select>
                <p>{{ form.featured_keyboards.error }}</p>
            </section>

            <section class="s-form s-lightgrey">
                <p>{% trans "The post's title" %}</p>
                <label class="green" for="title">keeby-talk:~$ title</label><br>
                <span class="green">keeby-talk:~$ </span><br>
                <textarea class="t-input large" name="title" rows="2" cols="50">{{ form.title.value }}</textarea>
            </section>

            <section class="s-form s-lightgrey">
                <p>{% trans "The post's content" %}</p>
                <label class="green" for="title">keeby-talk:~$ content -text</label><br>
                <span class="green">keeby-talk:~$ </span><br>
                <textarea class="t-input large" name="content" rows="5" cols="50">{{ form.content.value }}</textarea>
            </section>

            <input class="t-input" type="submit" value="keeby-talk:~$ post -update">
        </form>

    </section>

{% endblock %}

templates/templates/auth.html
{% extends "templates/global/base.html" %}

{% block asides %}
    <!-- The "login" template does not include any asides. -->
{% endblock %}

templates/templates/default.html
{% extends "templates/global/base.html" %}

{% block asides %}
    <aside>
        <!-- The currents template asides. -->
        {% include "templates/default/aside.html" %}
        <!-- The global asides. -->
        {% include "templates/global/aside.html" %}
    </aside>
{% endblock %}

templates/templates/default/aside.html
{% load i18n %}

<section class="default s-green section-aside">
    <h3>{% trans "Keyboards" %}</h3>
    <ul>
        {% for keeb in keebs %}
            <li><p><a class="t-link green" href="{% url "app_keeb_detail" keeb.pk %}">{{ keeb.name }} ({{ keeb.keys }} {% trans "keys" %})</a></p></li>
        {% endfor %}
    </ul>
</section>

templates/templates/global/aside.html
{% load i18n %}

<section class="default s-grey section-aside">
    <p><a class="t-link darkgrey underline" href="{% url "app_not_working_yet" %}">{% trans "Legal terms" %}</a></p>
    <p><a class="t-link darkgrey underline" href="{% url "app_not_working_yet" %}">{% trans "Content policy" %}</a></p>
    <p class="darkgrey">Keeby Talk @ 2020 ({% trans "no copyright" %})</p>
</section>

templates/templates/global/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="{% get_current_language as LANGUAGE_CODE %}">
<head>
    <!-- The global head elements. -->
    <meta charset="utf-8">
    <title>{{ title }} | KEEBY TALK</title>
    <meta name="description" content="{% trans "The one and only place to really talk about keyboards!" %}">
    <meta name="author" content="Alexis Philip">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
</head>
<body>

<!-- The global header. -->
{% include "templates/global/header.html" %}

<main>
    <section class="wrapper">
        <section class="content">
            <!-- The main view. -->
            {% block content %}{% endblock %}
        </section>
        <!-- The asides. -->
        {% block asides %}{% endblock %}
    </section>
</main>

</body>
</html>

templates/templates/global/header.html
{% load i18n %}

<header>
    <h2 class="main-title">
        <a class="t-link green no-underline" href="{% url "app_home" %}">KEEBY TALK</a>
    </h2>
    <nav>
        {% if user.is_authenticated %}
            <p class="btn-green green"><a class="t-link no-underline" href="{% url "app_post_create" %}">{% trans "post[create]" %}</a></p>
            <p class="darkgrey"><a class="t-link" href="{% url "app_profile" %}">{% trans "profile" %}[{{ user.username }}]</a></p>
            <p class="darkgrey"><a class="t-link" href="{% url "app_log_out" %}">{% trans "log[out]" %}</a></p>
        {% else %}
            <p class="darkgrey"><a class="t-link" href="{% url "app_log_in" %}">{% trans "log[in]" %}</a></p>
        {% endif %}
    </nav>
</header>

templates/templates/keyboard.html
{% extends "templates/global/base.html" %}

{% block asides %}
    <aside>
        <!-- The currents template asides. -->
        {% include "templates/keyboard/aside.html" %}
        <!-- The global asides. -->
        {% include "templates/global/aside.html" %}
    </aside>
{% endblock %}

templates/templates/keyboard/aside.html
{% load i18n %}

<section class="default s-grey section-aside s-border">
    <h3>Description</h3>
    <p>{% trans "keys" %}[{{ object.keys }}]</p>
    <p>{% trans "created_on" %}[{{ object.release_date }}]</p>

    <a class="t-link no-underline" href="{% url "app_not_working_yet" %}">
        <p class="btn-green green">{% trans "follow" %}</p>
    </a>
</section>

templates/user/profile.html
{% extends "templates/../templates/default.html" %}

{% load static i18n %}

{% block content %}

    <section class="s-user s-lightgrey">

        <section class="s-user-header">
            <h2>{{ user.username }}</h2>
        </section>

        <section class="s-user-hotbar s-grey">
            <p><a class="t-link green underline" href="{% url "app_not_working_yet" %}">{% trans "update[email]" %}</a></p>
            <p><a class="t-link green underline" href="{% url "app_not_working_yet" %}">{% trans "update[avatar]" %}</a></p>
        </section>

        <h3>{% trans "My recent activity" %}</h3>

        {% for post in posts %}

            <a href="{% url "app_post_detail" post.pk %}">
                <section class="s-activity-element s-lightgrey s-highlight">
                    <div class="s-activity-head">
                        <div class="s-activity-wrapper">
                            <img class="s-activity-logo" src="{% static "img/icons/post.svg" %}" alt="Post icon.">
                            <p class="darkgrey">
                                <span class="green underline">{{ post.author }}</span>
                                {% trans "posted on" %}
                                <span class="grey underline">---</span>
                            </p>
                        </div>
                        <p class="darkgrey">{{ post.creation_date|date:"Y-m-d" }}</p>
                    </div>
                    <div class="s-activity-body">
                        <div>
                            <h3>{{ post.title }}</h3>
                            <p>{{ post.content }}</p>
                        </div>
                    </div>
                </section>
            </a>

        {% endfor %}

    </section>

{% endblock %}

templates/user/user_detail.html
{% extends "templates/../templates/default.html" %}

{% load static i18n %}

{% block content %}

    <section class="s-user s-lightgrey">

        <section class="s-user-header">
            <h2>{{ object.username }}</h2>
        </section>

        <section class="s-user-hotbar s-grey">
            <p>total_posts[{{ posts.all.count }}]</p>
        </section>

        <h3>{% trans "activity-prefix" %}{{ object.username }}{% trans "activity-suffix" %}</h3>

        {% for post in posts %}

            <a href="{% url "app_post_detail" post.pk %}">
                <section class="s-activity-element s-lightgrey s-highlight">
                    <div class="s-activity-head">
                        <div class="s-activity-wrapper">
                            <img class="s-activity-logo" src="{% static "img/icons/post.svg" %}" alt="Post icon.">
                            <p class="darkgrey">
                                <span class="green underline">{{ post.author }}</span>
                                {% trans "posted on" %}
                                <span class="grey underline">---</span>
                            </p>
                        </div>
                        <p class="darkgrey">{{ post.creation_date|date:"Y-m-d" }}</p>
                    </div>
                    <div class="s-activity-body">
                        <div>
                            <h3>{{ post.title }}</h3>
                            <p>{{ post.content }}</p>
                        </div>
                    </div>
                </section>
            </a>

        {% endfor %}

    </section>

{% endblock %}